syntax = "proto3";

option csharp_namespace = "RateLimiter.Writer";
package writer;

service Writer {
  rpc CreateLimit (CreateLimitRequest) returns (CreateLimitResponse);
  rpc GetLimitByRoute (GetLimitByRouteRequest) returns (GetLimitByRouteResponse);
  rpc UpdateLimit (UpdateLimitRequest) returns (UpdateLimitResponse);
  rpc DeleteLimit (DeleteLimitRequest) returns (DeleteLimitResponse);
}

message RateLimitModel {
  string route = 1;
  int32 requests_per_minute = 2;
}

message CreateLimitRequest {
  string route = 1;
  int32 requests_per_minute = 2;
}

message CreateLimitResponse {
  bool success = 1;
}

message GetLimitByRouteRequest {
  string route = 1;
}

message GetLimitByRouteResponse {
  optional RateLimitModel limit = 1;
}

message UpdateLimitRequest {
  string route = 1;
  int32 requests_per_minute = 2;
}

message UpdateLimitResponse {
  bool success = 1;
}

message DeleteLimitRequest {
  string route = 1;
}

message DeleteLimitResponse {
  bool success = 1;
}